### ISSUE TITLE
`ridibooks/php-core` 의존성 제거

### ISSUE THREAD

**Issue by namenu** [ridibooks/platform-common#14]
본 패키지가 플랫폼팀 모듈에 전반에 사용되고 있어 php-core의 버전 호환이 문제가 되고 있습니다.

1. MsgException
2. GnfConnectionProvider
3. SentryHelper

위 세 가지 기능을 위해 php-core에 의존하고 있으나, 1&2는 플랫폼팀에서만 사용되므로 단순히 옮기면 됩니다.
3은 구현을 그대로 가져오는 것이 전체를 참조하는 것 보다는 이득인 상황입니다.

**Comment by ssaifriend** [comment]
1,3은 그대로 옮기는게 좋은 방향일 것 같습니다.
그런데, 2번 GnfConnectionProvider에서 ConnectionProvider를 참조하고 있는데,
ConnectionProvider 참조를 걷어내고 내부 코드 일부를 GnfConnectionProvider로 옮기는게 좋을 것 같습니다.
