### ISSUE TITLE
Sentry SDK 업데이트

### ISSUE THREAD

**Issue by kiding** [ridibooks/platform-common#25]
https://github.com/ridi/platform-common/blob/c50fd69390ebaf57f4cf5a3318c1e353e855323f/composer.json#L11

platform-common에서 사용하는 Sentry PHP SDK *Raven* ^1.10은 [deprecate 되었으며](https://docs.sentry.io/clients/php/), PHP 7.1 이상에서 사용 가능한 [최신 Unified PHP SDK가 권장되고 있습니다.](https://docs.sentry.io/platforms/php/)

**Comment by ssaifriend** [comment]
#29 에서 해결 됨
